[project]
name = "crypto-streaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka>=2.13.0",
    "joblib>=1.5.3",
    "loguru>=0.7.3",
    "numpy>=2.4.2",
    "orjson>=3.11.7",
    "pandas>=3.0.1",
    "pydantic>=2.12.5",
    "python-json-logger>=4.0.0",
    "scikit-learn>=1.8.0",
    "statsd>=4.0.1",
    "websockets>=16.0",
]
